dist: focal

arch: amd64

language: c

compiler:
- gcc
- clang

env:
  global:
  # Encrypted COVERITY_SCAN_TOKEN
  - secure: "BQDASY4yNtsHV5bX6CDcFux4csQ4lkKm+Ihjwslab6XVOX8YAQrFeq6bHw+eCl8uCybrwUCOHYavvCHAFIBp5ik5D/NZUid+U1Yk1DSw6NcXpLMhEZDx9GVupyjExwFCOHMGnIRXcOI1mEMMaPHQQZWKixTVZX9350Dku6Qu3AXFjTSf3aCQLoazxGoNQveefmaqLLOg/kUgfGQV2eW8J4b9UKw3mdaDa651jdLaAOvKunRlI22j675JkFE45f0+RG/DtqSEfoDc3eAnsSebl9bj9JPNS4qgXschM0WaDUoogJFKcZ+OeLRPGQDGZUvCmvBE7mprOiFYtkFihAZmVpZ7pT1kgtmEnyuRX0+yaJN/YW+EQ5Nht89c5pM5BxInDXlyQWW1Kn9qXacpdIA8YTKswxa58tWQJp7c6oqaCrN5dUV3QvRJFLMxCMI3Ptjl196G4lZvVlT5ZyoYYnIhDmwoTrI1rhjKpnOQG9Ce64Jdlaf6c+5GPXHoqDSc8/zRWTVZrJJWnFStTSakLNDmdZtVO2bj5EQnMRgcaxK9uwmxRAUJvcocq1KKvkByesLD/5bH3d+gM9LL0NcJKjPRqgPL2amjXXqBuGRo9MSiEicgFPZ6inV/MUZGdTO4Lzr/8X5gqUl3cuvjybTDlu4izBSn3iCt5yZCQb2mtTx7m18="
  - CFLAGS="-Werror"
  - DISTCHECK_CONFIGURE_FLAGS='${CONFIGURE_FLAGS}'
  - TEST_LONG="t"
  - chain_lint="t"
  - root="/tmp/munge-test-$$"
  - verbose="t"
  jobs:
  - CONFIGURE_FLAGS="--enable-debug --with-crypto-lib=libgcrypt"
  - CONFIGURE_FLAGS="--enable-debug --with-crypto-lib=openssl"
  - CONFIGURE_FLAGS="--disable-debug --with-crypto-lib=libgcrypt"
  - CONFIGURE_FLAGS="--disable-debug --with-crypto-lib=openssl"

jobs:
  include:
  - arch: arm64
    env: CONFIGURE_FLAGS="--with-crypto-lib=libgcrypt" TEST_LONG=
  - arch: arm64
    env: CONFIGURE_FLAGS="--with-crypto-lib=openssl" TEST_LONG=
  - arch: ppc64le
    env: CONFIGURE_FLAGS="--with-crypto-lib=libgcrypt" TEST_LONG=
  - arch: ppc64le
    env: CONFIGURE_FLAGS="--with-crypto-lib=openssl" TEST_LONG=

addons:
  apt:
    packages:
    - zlib1g-dev
    - libbz2-dev
    - libgcrypt20-dev
    - libssl-dev
    - valgrind
    - valgrind-dbg
  coverity_scan:
    project:
      name: "dun/munge"
      description: "MUNGE Uid 'N' Gid Emporium"
    notification_email: cdunlap@llnl.gov
    build_command_prepend: "./bootstrap && ./configure"
    build_command: "make"
    branch_pattern: coverity_scan

before_install:
- test "${TRAVIS_BRANCH}" != "coverity_scan" -o "${TRAVIS_JOB_NUMBER##*.}" = "1" || exit 0

script:
- umask 022
- test "${TRAVIS_BRANCH}" != "coverity_scan" || exit 0
- ./bootstrap && ./configure ${CONFIGURE_FLAGS} && make -e -k && make -e distcheck

after_failure:
- grep -q "configure[:] exit 1" "config.log" && cat "config.log"
- find . -type f -name "test-suite.log" -execdir cat {} \;
- find . -type f -name "valgrind.log*" -execdir cat {} \;
- sleep 2 # config.log gets truncated without this final sleep
